version: "2.0"
services:
  postgres:
    build: ./database
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ilovepostgres
  
  phpPgAdmin:
    container_name: phppgadmin
    image: fizix/docker-pgadmin:php-fpm-environment
    environment:
      - POSTGRESQL_HOST=postgres
      - POSTGRESQL_PORT=5432
      - POSTGRESQL_DEFAULT_DB=postgres
    ports:
      - 80:80
    links:
      - postgres

  backend:  
    build: ./backend
    ports: 
      - "3000:3000"
    volumes:
      - ./backend:/go/src/github.com/merqure/backend
    depends_on:
      - postgres