version: "2.0"
services:
  postgres:
    build: ./database
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ilovemerqure

  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - postgres

  backend:  
    build: ./backend
    ports: 
      - "3000:3000"
    volumes:
      - ./backend:/go/src/github.com/merqure/backend
    depends_on:
      - postgres